name: CPack

on:
  push:
    tags:
      - "*.*.*"

jobs: 
  build_packages_Linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for release creation and file uploads
      packages: write  # Required for package operations

    steps:
    - uses: actions/checkout@v4

    - name: Configure Solver
      run: cmake -B ${{github.workspace}}/.build -D PRINT_VERSION=${{ github.ref_name }}

    - name: Build Solver
      run: cmake --build ${{github.workspace}}/.build

    # Remove sudo to avoid permission issues
    - name: Build package
      run: cmake --build ${{github.workspace}}/.build --target package

    - name: Build source package
      run: cmake --build ${{github.workspace}}/.build --target package_source

    # Verify files exist before release
    - name: Check artifacts exist
      run: ls -la .build/*.deb .build/*.tar.gz .build/*.zip

    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifacts: ".build/*.deb,.build/*.tar.gz,.build/*.zip"
        tag: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly pass the token

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: solver
        path: ${{github.workspace}}/.build/solver
