name: CPack

on:
  push:
    tags:
      - "*.*.*"

jobs: 
  build_packages_Linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for releases
      packages: write  # Required for packages
      id-token: write  # Required for GitHub OIDC

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for tags

    - name: Configure Solver
      run: cmake -B ${{github.workspace}}/.build -D PRINT_VERSION=${{ github.ref_name }}

    - name: Build Solver
      run: cmake --build ${{github.workspace}}/.build

    - name: Build package
      run: cmake --build ${{github.workspace}}/.build --target package

    - name: Build source package
      run: cmake --build ${{github.workspace}}/.build --target package_source

    - name: Verify artifacts
      run: ls -la .build/*.deb .build/*.tar.gz .build/*.zip

    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifacts: ".build/*.deb,.build/*.tar.gz,.build/*.zip"
        tag: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: solver
        path: ${{github.workspace}}/.build/solver*
