name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm libfmt-dev cmake
          
      - name: Build and package
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $(nproc)
          cd build && cpack -G DEB -G RPM
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            build/*.deb
            build/*.rpm

  macos-package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: brew install cmake
      
      - name: Build and package
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $(sysctl -n hw.ncpu)
          cd build && cpack -G DragNDrop
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-package
          path: build/*.dmg

  windows-package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install WiX
        run: choco install wixtoolset -y
      
      - name: Build and package
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 ..
          cmake --build . --config Release
          cpack -G WIX
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: build/*.msi

  create-release:
    needs: [linux-packages, macos-package, windows-package]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: List artifacts (debug)
        run: ls -R artifacts
          
      - name: Create source archives
        run: |
          git archive --format=tar.gz HEAD -o source.tar.gz
          git archive --format=zip HEAD -o source.zip
          
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/linux-packages/*.deb
            artifacts/linux-packages/*.rpm
            artifacts/macos-package/*.dmg
            artifacts/windows-package/*.msi
            source.tar.gz
            source.zip
